local AbilityData = {
	["Ability"] = {
	--Ash
		["Shuriken"] = {
			Cost = 25,
			Key = 1,
			Description = "Launches a spinning blade of pain, dealing high damage and impaling enemies to walls.",
			CardImage = "ShurikenModx256.png",
			DarkIcon = "Shuriken130xDark.png",
			WhiteIcon = "Shuriken130xWhite.png",
			Warframe = "Ash",
		},
		["Smoke Screen"] = {
			Cost = 35,
			Key = 2,
			Description = "Drops a smoke bomb that stuns enemies and obscures their vision, rendering Ash invisible for a short time.",
			CardImage = "SmokeScreenModx256.png",
			DarkIcon = "SmokeScreen130xDark.png",
			WhiteIcon = "SmokeScreen130xWhite.png",
			Warframe = "Ash",
		},
		["Teleport"] = {
			Cost = 25,
			Key = 3,
			Description = "Ash teleports towards the target, bringing him into melee range and making enemies vulnerable to finishers.",
			CardImage = "TeleportModx256.png",
			DarkIcon = "Teleport130xDark.png",
			WhiteIcon = "Teleport130xWhite.png",
			Warframe = "Ash",
		},
		["Blade Storm"] = {
			Cost = 0,
			Key = 4,
			Description = "Project fierce shadow clones of Ash upon groups of distant enemies. Join the fray using Teleport.",
			CardImage = "BladeStormModx256.png",
			DarkIcon = "BladeStorm130xDark.png",
			WhiteIcon = "BladeStorm130xWhite.png",
			Warframe = "Ash",
		},
	--Atlas
		["Landslide"] = {
			Cost = 25,
			Key = 1,
			Description = "Bash enemies with an exploding sliding punch, and repeat for a devastating combo. Petrified enemies take extra damage, and drop Rubble when destroyed. Rubble can heal Atlas and bolster his armor.",
			CardImage = "LandslideModx256.png",
			DarkIcon = "Landslide130xDark.png",
			WhiteIcon = "Landslide130xWhite.png",
			Warframe = "Atlas",
		},
		["Tectonics"] = {
			Cost = 50,
			Key = 2,
			Description = "Summon a rock-wall, activate again to send the rocks crashing towards the enemy.",
			CardImage = "TectonicsModx256.png",
			DarkIcon = "Tectonics130xDark.png",
			WhiteIcon = "Tectonics130xWhite.png",
			Warframe = "Atlas",
		},
		["Petrify"] = {
			Cost = 75,
			Key = 3,
			Description = "Atlas' hardened gaze will fossilize foes, heal Rumblers, and create Petrified Bulwarks. When shattered, petrified enemies drop healing Rubble for Atlas.",
			CardImage = "PetrifyModx256.png",
			DarkIcon = "Petrify130xDark.png",
			WhiteIcon = "Petrify130xWhite.png",
			Warframe = "Atlas",
		},
		["Rumblers"] = {
			Cost = 100,
			Key = 4,
			Description = "Summon two elemental stone brawlers to the melee. Summoning petrifies enemies in close proximity to Atlas. When finished, Rumblers collapse into a pile of healing Rubble.",
			CardImage = "RumblersModx256.png",
			DarkIcon = "Rumblers130xDark.png",
			WhiteIcon = "Rumblers130xWhite.png",
			Warframe = "Atlas",
		},
	--Banshee
		["Sonic Boom"] = {
			Cost = 25,
			Key = 1,
			Description = "Banshee emits a sonic shockwave that pushes targets in range with enough force to incapacitate or kill attackers.",
			CardImage = "SonicBoomModx256.png",
			DarkIcon = "SonicBoom130xDark.png",
			WhiteIcon = "SonicBoom130xWhite.png",
			Warframe = "Banshee",
		},
		["Sonar"] = {
			Cost = 50,
			Key = 2,
			Description = "Using acoustic location, Banshee's Sonar power finds and tracks enemies, and exposes critical weak spots to everyone in your squad.",
			CardImage = "SonarModx256.png",
			DarkIcon = "Sonar130xDark.png",
			WhiteIcon = "Sonar130xWhite.png",
			Warframe = "Banshee",
		},
		["Silence"] = {
			Cost = 75,
			Key = 3,
			Description = "Using Silence surrounds Banshee in an aura that stuns enemies and will limit their perceptions and tactical response to gunfire and Warframe attacks.",
			CardImage = "SilenceModx256.png",
			DarkIcon = "Silence130xDark.png",
			WhiteIcon = "Silence130xWhite.png",
			Warframe = "Banshee",
		},
		["Sound Quake"] = {
			Cost = 25,
			Key = 4,
			Description = "Channeling all of her acoustic energy into the environment, Banshee uses ultrasonic reverberations to violently shake the ground.",
			CardImage = "SoundQuakeModx256.png",
			DarkIcon = "SoundQuake130xDark.png",
			WhiteIcon = "SoundQuake130xWhite.png",
			Warframe = "Banshee",
		},
	--Baruuk
		["Elude"] = {
			Cost = 25,
			Key = 1,
			Description = "Dodge all incoming projectiles, but only while not attacking. Use again to deactivate this ability.",
			CardImage = "EludeModx256.png",
			DarkIcon = "Elude130xDark.png",
			WhiteIcon = "Elude130xWhite.png",
			Warframe = "Baruuk",
		},
		["Lull"] = {
			Cost = 50,
			Key = 2,
			Description = "A calming wave slows enemies until they fall into a slumber. Enemies woken by damage will be confused and disoriented. Short-term amnesia means all waking enemies forget anything that happened before the lull.",
			CardImage = "LullModx256.png",
			DarkIcon = "Lull130xDark.png",
			WhiteIcon = "Lull130xWhite.png",
			Warframe = "Baruuk",
		},
		["Desolate Hands"] = {
			Cost = 75,
			Key = 3,
			Description = "Summon a bevy of orbiting daggers to seek out enemy guns, destroying them with a small explosion. Combine with Elude to double the range. ",
			CardImage = "DesolateHandsModx256.png",
			DarkIcon = "DesolateHands130xDark.png",
			WhiteIcon = "DesolateHands130xWhite.png",
			Warframe = "Baruuk",
		},
		["Serene Storm"] = {
			Cost = 25,
			Key = 4,
			Description = "With his Restraint eroded, Baruuk commands the Desert Wind to deliver powerful radial strikes with his fists and feet. Each moment commanding the storm restores his Restraint.",
			CardImage = "SereneStormModx256.png",
			DarkIcon = "SereneStorm130xDark.png",
			WhiteIcon = "SereneStorm130xWhite.png",
			Warframe = "Baruuk",
		},
	--Chroma
		["Spectral Scream"] = {
			Cost = 10,
			Key = 1,
			Description = "Exhale a deep breath of elemental destruction. Chroma's energy color determines the element.",
			CardImage = "SpectralScreamModx256.png",
			DarkIcon = "SpectralScream130xDark.png",
			WhiteIcon = "SpectralScream130xWhite.png",
			Warframe = "Chroma",
		},
		["Elemental Ward"] = {
			Cost = 50,
			Key = 2,
			Description = "Depending on Chroma's elemental alignment, an offensive area-of-effect is created. Chroma and his nearby allies are imbued with defensive energy.",
			CardImage = "ElementalWardModx256.png",
			DarkIcon = "ElementalWard130xDark.png",
			WhiteIcon = "ElementalWard130xWhite.png",
			Warframe = "Chroma",
		},
		["Vex Armor"] = {
			Cost = 75,
			Key = 3,
			Description = "When shields are hit, Chroma's armor grows stronger, when health takes a hit, weapon damage increases. Active for a limited time, maximum increases correspond to rank.",
			CardImage = "VexArmorModx256.png",
			DarkIcon = "VexArmor130xDark.png",
			WhiteIcon = "VexArmor130xWhite.png",
			Warframe = "Chroma",
		},
		["Effigy"] = {
			Cost = 50,
			Key = 4,
			Description = "Chroma turns his pelt into a massive sentry that strengthens nearby allies and engulfs enemies in elemental attacks.",
			CardImage = "EffigyModx256.png",
			DarkIcon = "Effigy130xDark.png",
			WhiteIcon = "Effigy130xWhite.png",
			Warframe = "Chroma",
		},
	--Ember
		["Fireball"] = {
			Cost = 25,
			Key = 1,
			Description = "Charge and release a fiery projectile that ignites enemies on contact and leaves behind a treacherous patch of flame.",
			CardImage = "FireballModx256.png",
			DarkIcon = "Fireball130xDark.png",
			WhiteIcon = "Fireball130xWhite.png",
			Warframe = "Ember",
		},
		["Accelerant"] = {
			Cost = 50,
			Key = 2,
			Description = "Stun nearby enemies with strong accelerant. Increases all fire damage dealt.",
			CardImage = "AccelerantModx256.png",
			DarkIcon = "Accelerant130xDark.png",
			WhiteIcon = "Accelerant130xWhite.png",
			Warframe = "Ember",
		},
		["Fire Blast"] = {
			Cost = 75,
			Key = 3,
			Description = "Slam the ground to create a wave of plasma that incinerates nearby enemies and forms a persistent ring of fire. Add heat damage to weapons by firing them through the ring.",
			CardImage = "FireBlastModx256.png",
			DarkIcon = "FireBlast130xDark.png",
			WhiteIcon = "FireBlast130xWhite.png",
			Warframe = "Ember",
		},
		["World On Fire"] = {
			Cost = 50,
			Key = 4,
			Description = "Blast nearby foes with a burst of fire, and follow that up with a barrage of fireballs against any enemy who dares approach. Over time, these fireballs burn hotter as they consume more energy.",
			CardImage = "WorldOnFireModx256.png",
			DarkIcon = "WorldOnFire130xDark.png",
			WhiteIcon = "WorldOnFire130xWhite.png",
			Warframe = "Ember",
		},
	--Equinox
		["Metamorphosis"] = {
			Cost = 25,
			Key = 1,
			Description = "Switch forms, temporarily gaining bonus shields and armor in Night-Form, or bonus damage and speed in Day-Form.",
			CardImage = "MetamorphosisModx256.png",
			DarkIcon = "Metamorphosis130xDark.png",
			WhiteIcon = "Metamorphosis130xWhite.png",
			Warframe = "Equinox",
		},
		["Rest & Rage"] = {
			Cost = 25,
			Key = 2,
			Description = "In Night Form targets are put to sleep. In Day Form targets become more vulnerable to damage. ",
			CardImage = "RestRageModx256.png",
			DarkIcon = "RestRage130xDark.png",
			WhiteIcon = "RestRage130xWhite.png",
			Warframe = "Equinox",
		},
		["Pacify & Provoke"] = {
			Cost = 10,
			Key = 3,
			Description = "In Night Form reduces damage inflicted by nearby enemies. In Day Form increases Ability Strength of nearby allies.",
			CardImage = "PacifyProvokeModx256.png",
			DarkIcon = "PacifyProvoke130xDark.png",
			WhiteIcon = "PacifyProvoke130xWhite.png",
			Warframe = "Equinox",
		},
		["Mend & Maim"] = {
			Cost = 50,
			Key = 4,
			Description = "In Night Form, allies are healed with each nearby enemy killed. In Day Form, nearby enemies are bled and then subjected to a wave of slashing force.",
			CardImage = "MendMaimModx256.png",
			DarkIcon = "MendMaim130xDark.png",
			WhiteIcon = "MendMaim130xWhite.png",
			Warframe = "Equinox",
		},
	--Excalibur
		["Slash Dash"] = {
			Cost = 25,
			Key = 1,
			Description = "Dash between enemies while slashing with the Exalted Blade.",
			CardImage = "SlashDashModx256.png",
			DarkIcon = "SlashDash130xDark.png",
			WhiteIcon = "SlashDash130xWhite.png",
			Warframe = "Excalibur",
		},
		["Radial Blind"] = {
			Cost = 50,
			Key = 2,
			Description = "Emits a bright flash of light, blinding all enemies in a small radius for several seconds.",
			CardImage = "RadialBlindModx256.png",
			DarkIcon = "RadialBlind130xDark.png",
			WhiteIcon = "RadialBlind130xWhite.png",
			Warframe = "Excalibur",
		},
		["Radial Javelin"] = {
			Cost = 75,
			Key = 3,
			Description = "Launches javelins towards enemies, dealing high damage and impaling them to walls.",
			CardImage = "RadialJavelinModx256.png",
			DarkIcon = "RadialJavelin130xDark.png",
			WhiteIcon = "RadialJavelin130xWhite.png",
			Warframe = "Excalibur",
		},
		["Exalted Blade"] = {
			Cost = 25,
			Key = 4,
			Description = "Summon a sword of pure light and immense power.",
			CardImage = "ExaltedBladeModx256.png",
			DarkIcon = "ExaltedBlade130xDark.png",
			WhiteIcon = "ExaltedBlade130xWhite.png",
			Warframe = "Excalibur",
		},
	--Umbra's Radial Blind
		["Radial Howl"] = {
			Cost = 50,
			Key = 2,
			Description = "Let out a ferocious howl that stuns nearby enemies and causes Sentients to shed any built up resistances.",
			CardImage = "RadialHowlModx256.png",
			DarkIcon = "RadialHowl130xDark.png",
			WhiteIcon = "RadialHowl130xWhite.png",
			Warframe = "Excalibur Umbra",
		},
	--Frost
		["Freeze"] = {
			Cost = 25,
			Key = 1,
			Description = "A frigid energy blast that freezes targets in their tracks.",
			CardImage = "FreezeModx256.png",
			DarkIcon = "Freeze130xDark.png",
			WhiteIcon = "Freeze130xWhite.png",
			Warframe = "Frost",
		},
		["Ice Wave"] = {
			Cost = 50,
			Key = 2,
			Description = "Sends a wave of razor sharp, crystallized ice toward an enemy, dealing heavy damage.",
			CardImage = "IceWaveModx256.png",
			DarkIcon = "IceWave130xDark.png",
			WhiteIcon = "IceWave130xWhite.png",
			Warframe = "Frost",
		},
		["Snow Globe"] = {
			Cost = 50,
			Key = 3,
			Description = "Frost deep freezes any vapor and moisture in the area, creating a protective sphere with brief invulnerability to boost its strength.",
			CardImage = "SnowGlobeModx256.png",
			DarkIcon = "SnowGlobe130xDark.png",
			WhiteIcon = "SnowGlobe130xWhite.png",
			Warframe = "Frost",
		},
		["Avalanche"] = {
			Cost = 100,
			Key = 4,
			Description = "Summons a treacherous landslide of ice that instantly freezes and shatters all enemies in its radius.",
			CardImage = "AvalancheModx256.png",
			DarkIcon = "Avalanche130xDark.png",
			WhiteIcon = "Avalanche130xWhite.png",
			Warframe = "Frost",
		},
	--Gara
		["Shattered Lash"] = {
			Cost = 25,
			Key = 1,
			Description = "Lash out with stream of shattered glass, or hold for an arcing strike.",
			CardImage = "ShatteredLashModx256.png",
			DarkIcon = "ShatteredLash130xDark.png",
			WhiteIcon = "ShatteredLash130xWhite.png",
			Warframe = "Gara",
		},
		["Splinter Storm"] = {
			Cost = 50,
			Key = 2,
			Description = "Gara's armor splinters into a maelstrom of shattered glass that slices enemies and impairs their weapons. Allies who contact the cloud are fortified against damage.",
			CardImage = "SplinterStormModx256.png",
			DarkIcon = "SplinterStorm130xDark.png",
			WhiteIcon = "SplinterStorm130xWhite.png",
			Warframe = "Gara",
		},
		["Spectrorage"] = {
			Cost = 75,
			Key = 3,
			Description = "Trap enemies in a carousel of mirrors, forcing them to attack visions of their true selves. Destroyed mirrors damage their attackers, as does the collapse of the carousel.",
			CardImage = "SpectrorageModx256.png",
			DarkIcon = "Spectrorage130xDark.png",
			WhiteIcon = "Spectrorage130xWhite.png",
			Warframe = "Gara",
		},
		["Mass Vitrify"] = {
			Cost = 75,
			Key = 4,
			Description = "Create an expanding ring of molten glass that slowly crystallizes enemies who enter. When the expansion is complete, the ring hardens to block weapons fire. The ring draws extra strength from the health and shields of crystallized enemies. Use Shattered Lash to smash the ring and send razor-sharp glass flying outward.",
			CardImage = "MassVitrifyModx256.png",
			DarkIcon = "MassVitrify130xDark.png",
			WhiteIcon = "MassVitrify130xWhite.png",
			Warframe = "Gara",
		},
	--Garuda
		["Dread Mirror"] = {
			Cost = 25,
			Key = 1,
			Description = "Rip the life force from an enemy and use it as a shield that captures damage. Charge to channel the captured damage into an explosive projectile.",
			CardImage = "DreadMirrorModx256.png",
			DarkIcon = "DreadMirror130xDark.png",
			WhiteIcon = "DreadMirror130xWhite.png",
			Warframe = "Garuda",
		},
		["Blood Altar"] = {
			Cost = 50,
			Key = 2,
			Description = "Impale an enemy on an altar of talons and siphon health for Garuda and her allies.",
			CardImage = "BloodAltarModx256.png",
			DarkIcon = "BloodAltar130xDark.png",
			WhiteIcon = "BloodAltar130xWhite.png",
			Warframe = "Garuda",
		},
		["Bloodletting"] = {
			Cost = 0,
			Key = 3,
			Description = "Garuda sacrifices her health to generate energy.",
			CardImage = "BloodlettingModx256.png",
			DarkIcon = "Bloodletting130xDark.png",
			WhiteIcon = "Bloodletting130xWhite.png",
			Warframe = "Garuda",
		},
		["Seeking Talons"] = {
			Cost = 100,
			Key = 4,
			Description = "Charge to expand the targeting area, release to send Garuda’s talons careening toward each target in area. Surviving enemies are prone to bleeding.",
			CardImage = "SeekingTalonsModx256.png",
			DarkIcon = "SeekingTalons130xDark.png",
			WhiteIcon = "SeekingTalons130xWhite.png",
			Warframe = "Garuda",
		},
	--Harrow
		["Condemn"] = {
			Cost = 25,
			Key = 1,
			Description = "Cast a wave of energy that chains them where they stand. Each enemy held reinforces Harrow’s shields.",
			CardImage = "CondemnModx256.png",
			DarkIcon = "Condemn130xDark.png",
			WhiteIcon = "Condemn130xWhite.png",
			Warframe = "Harrow",
		},
		["Penance"] = {
			Cost = 50,
			Key = 2,
			Description = "Sacrifice shields to boost reload, and fire rate while converting damage inflicted on enemies into health for Harrow and nearby allies.",
			CardImage = "PenanceModx256.png",
			DarkIcon = "Penance130xDark.png",
			WhiteIcon = "Penance130xWhite.png",
			Warframe = "Harrow",
		},
		["Thurible"] = {
			Cost = 25,
			Key = 3,
			Description = "Channel Harrow’s energy into the Thurible to generate a buff. Once finished, kill enemies to bestow nearby allies with bursts of energy. The more energy channeled the greater the reward for each kill. Headshots produce extra energy.",
			CardImage = "ThuribleModx256.png",
			DarkIcon = "Thurible130xDark.png",
			WhiteIcon = "Thurible130xWhite.png",
			Warframe = "Harrow",
		},
		["Covenant"] = {
			Cost = 100,
			Key = 4,
			Description = "Protect nearby allies with an energy force that absorbs all damage and converts it to a Critical Chance bonus for all those under the Covenant. Headshots are amplified even further.",
			CardImage = "CovenantModx256.png",
			DarkIcon = "Covenant130xDark.png",
			WhiteIcon = "Covenant130xWhite.png",
			Warframe = "Harrow",
		},
	--Hydroid
		["Tempest Barrage"] = {
			Cost = 25,
			Key = 1,
			Description = "Target an area and call down a barrage of liquid fury. Charge this attack to increase the lethality of the onslaught.",
			CardImage = "TempestBarrageModx256.png",
			DarkIcon = "TempestBarrage130xDark.png",
			WhiteIcon = "TempestBarrage130xWhite.png",
			Warframe = "Hydroid",
		},
		["Tidal Surge"] = {
			Cost = 50,
			Key = 2,
			Description = "Crash through enemies in a ferocious wall of water.",
			CardImage = "TidalSurgeModx256.png",
			DarkIcon = "TidalSurge130xDark.png",
			WhiteIcon = "TidalSurge130xWhite.png",
			Warframe = "Hydroid",
		},
		["Undertow"] = {
			Cost = 15,
			Key = 3,
			Description = "Become a water trap and drown unsuspecting enemies. ",
			CardImage = "UndertowModx256.png",
			DarkIcon = "Undertow130xDark.png",
			WhiteIcon = "Undertow130xWhite.png",
			Warframe = "Hydroid",
		},
		["Tentacle Swarm"] = {
			Cost = 50,
			Key = 4,
			Description = "Tap to spawn watery tentacles from all nearby surfaces to wreak havoc. Charge to increase the number of tentacles and spawn area. Use while in Undertow to have the tentacles emerge from the pool.",
			CardImage = "TentacleSwarmModx256.png",
			DarkIcon = "TentacleSwarm130xDark.png",
			WhiteIcon = "TentacleSwarm130xWhite.png",
			Warframe = "Hydroid",
		},
	--Inaros
		["Desiccation"] = {
			Cost = 25,
			Key = 1,
			Description = "Blast enemies with a wave of cursed sand that blinds them and steals their health.",
			CardImage = "DesiccationModx256.png",
			DarkIcon = "Desiccation130xDark.png",
			WhiteIcon = "Desiccation130xWhite.png",
			Warframe = "Inaros",
		},
		["Devour"] = {
			Cost = 50,
			Key = 2,
			Description = "Hold power to trap target in quicksand and draw them in for devouring; this steals health and ultimately creates a friendly Sand Shadow.",
			CardImage = "DevourModx256.png",
			DarkIcon = "Devour130xDark.png",
			WhiteIcon = "Devour130xWhite.png",
			Warframe = "Inaros",
		},
		["Sandstorm"] = {
			Cost = 75,
			Key = 3,
			Description = "Become a whirling spiral of sand that sends enemies flying and devours those trapped in quicksand.",
			CardImage = "SandstormModx256.png",
			DarkIcon = "Sandstorm130xDark.png",
			WhiteIcon = "Sandstorm130xWhite.png",
			Warframe = "Inaros",
		},
		["Scarab Swarm"] = {
			Cost = 25,
			Key = 4,
			Description = "Charge to transform health into hardened scarab armor. Discharge to blast enemies with a scarab swarm; survivors have their health drained and bestowed on allies.",
			CardImage = "ScarabSwarmModx256.png",
			DarkIcon = "ScarabSwarm130xDark.png",
			WhiteIcon = "ScarabSwarm130xWhite.png",
			Warframe = "Inaros",
		},
	--Ivara
		["Quiver"] = {
			Cost = 25,
			Key = 1,
			Description = "Cycle through and shoot one of four tactical arrows: Cloak, Dashwire, Noise and Sleep. In the Conclave, use the Null-Shield and Slow Arrows.",
			CardImage = "QuiverModx256.png",
			DarkIcon = "Quiver130xDark.png",
			WhiteIcon = "Quiver130xWhite.png",
			Warframe = "Ivara",
		},
		["Navigator"] = {
			Cost = 25,
			Key = 2,
			Description = "Assume control of a projectile and guide it to the target.",
			CardImage = "NavigatorModx256.png",
			DarkIcon = "Navigator130xDark.png",
			WhiteIcon = "Navigator130xWhite.png",
			Warframe = "Ivara",
		},
		["Prowl"] = {
			Cost = 25,
			Key = 3,
			Description = "Become invisible and steal loot from unsuspecting enemies or take out prey with deadly headshots.",
			CardImage = "ProwlModx256.png",
			DarkIcon = "Prowl130xDark.png",
			WhiteIcon = "Prowl130xWhite.png",
			Warframe = "Ivara",
		},
		["Artemis Bow"] = {
			Cost = 50,
			Key = 4,
			Description = "Summon a mighty bow and unleash a volley of devastating arrows.",
			CardImage = "ArtemisBowModx256.png",
			DarkIcon = "ArtemisBow130xDark.png",
			WhiteIcon = "ArtemisBow130xWhite.png",
			Warframe = "Ivara",
		},
	--Khora
		["Whipclaw"] = {
			Cost = 25,
			Key = 1,
			Description = "Send enemies reeling with a deafening whipcrack.",
			CardImage = "WhipclawModx256.png",
			DarkIcon = "Whipclaw130xDark.png",
			WhiteIcon = "Whipclaw130xWhite.png",
			Warframe = "Khora",
		},
		["Ensnare"] = {
			Cost = 50,
			Key = 2,
			Description = "Bind a hapless target in living metal, entangling others who stray too close. Whipclaw will refresh the trap allowing it to capture more enemies.",
			CardImage = "EnsnareModx256.png",
			DarkIcon = "Ensnare130xDark.png",
			WhiteIcon = "Ensnare130xWhite.png",
			Warframe = "Khora",
		},
		["Venari"] = {
			Cost = 0,
			Key = 3,
			Description = "Command Venari to focus on a target. Hold to cycle between Attack, Protect, and Heal postures. If Venari is killed, use this ability to revive her instantly.",
			CardImage = "VenariModx256.png",
			DarkIcon = "Venari130xDark.png",
			WhiteIcon = "Venari130xWhite.png",
			Warframe = "Khora",
		},
		["Strangledome"] = {
			Cost = 100,
			Key = 4,
			Description = "Weave a dome of living chain that ensnares and strangles any enemy within, and any foolish enough to approach. Foes outside the trap will try to hasten their comrade's deaths by shooting them. Crack Whipclaw on the dome to further damage any trapped enemies.",
			CardImage = "StrangledomeModx256.png",
			DarkIcon = "Strangledome130xDark.png",
			WhiteIcon = "Strangledome130xWhite.png",
			Warframe = "Khora",
		},
	--Limbo
		["Banish"] = {
			Cost = 25,
			Key = 1,
			Description = "Casts a wave of Rift energy that damages hostiles while pushing enemies and allies out of Limbo’s current plane of existence.",
			CardImage = "BanishModx256.png",
			DarkIcon = "Banish130xDark.png",
			WhiteIcon = "Banish130xWhite.png",
			Warframe = "Limbo",
		},
		["Stasis"] = {
			Cost = 50,
			Key = 2,
			Description = "Freezes Rift-bound enemies. While active, enemy projectiles are arrested in mid-air, resuming its trajectory when stasis ends.",
			CardImage = "StasisModx256.png",
			DarkIcon = "Stasis130xDark.png",
			WhiteIcon = "Stasis130xWhite.png",
			Warframe = "Limbo",
		},
		["Rift Surge"] = {
			Cost = 50,
			Key = 3,
			Description = "Surges nearby Rift-bound enemies with Rift energy. When killed the Rift Surge is transferred to a nearby enemy outside the rift. Surged enemies that leave the Rift perform a radial Banish.",
			CardImage = "RiftSurgeModx256.png",
			DarkIcon = "RiftSurge130xDark.png",
			WhiteIcon = "RiftSurge130xWhite.png",
			Warframe = "Limbo",
		},
		["Cataclysm"] = {
			Cost = 100,
			Key = 4,
			Description = "A violent blast of void energy tears open a pocket of rift plane which can sustain itself for a short period before collapsing in another lethal blast.",
			CardImage = "CataclysmModx256.png",
			DarkIcon = "Cataclysm130xDark.png",
			WhiteIcon = "Cataclysm130xWhite.png",
			Warframe = "Limbo",
		},
	--Loki
		["Decoy"] = {
			Cost = 25,
			Key = 1,
			Description = "Loki deploys a holographic copy of himself, drawing enemy fire.",
			CardImage = "DecoyModx256.png",
			DarkIcon = "Decoy130xDark.png",
			WhiteIcon = "Decoy130xWhite.png",
			Warframe = "Loki",
		},
		["Invisibility"] = {
			Cost = 50,
			Key = 2,
			Description = "Loki camouflages himself, becoming invisible to enemies.",
			CardImage = "InvisibilityModx256.png",
			DarkIcon = "Invisibility130xDark.png",
			WhiteIcon = "Invisibility130xWhite.png",
			Warframe = "Loki",
		},
		["Switch Teleport"] = {
			Cost = 25,
			Key = 3,
			Description = "Loki instantaneously swaps positions with a target, confusing the enemy.",
			CardImage = "SwitchTeleportModx256.png",
			DarkIcon = "SwitchTeleport130xDark.png",
			WhiteIcon = "SwitchTeleport130xWhite.png",
			Warframe = "Loki",
		},
		["Radial Disarm"] = {
			Cost = 100,
			Key = 4,
			Description = "Lets forth a wave of energy, disrupting the projectile weapons of enemies in range and forcing them to revert to melee combat.",
			CardImage = "RadialDisarmModx256.png",
			DarkIcon = "RadialDisarm130xDark.png",
			WhiteIcon = "RadialDisarm130xWhite.png",
			Warframe = "Loki",
		},
	--Mag
		["Pull"] = {
			Cost = 25,
			Key = 1,
			Description = "Magnetic force pulls enemies toward you, stunning them and bringing them into melee range.",
			CardImage = "PullModx256.png",
			DarkIcon = "Pull130xDark.png",
			WhiteIcon = "Pull130xWhite.png",
			Warframe = "Mag",
		},
		["Magnetize"] = {
			Cost = 50,
			Key = 2,
			Description = "Creates a magnetic field around a target, ensnaring nearby enemies and dealing damage over time. The field reacts to bullets and shards created from Polarize to increase the damage.",
			CardImage = "MagnetizeModx256.png",
			DarkIcon = "Magnetize130xDark.png",
			WhiteIcon = "Magnetize130xWhite.png",
			Warframe = "Mag",
		},
		["Polarize"] = {
			Cost = 75,
			Key = 3,
			Description = "Emit an energy pulse that depletes enemy shields and armor, creating shards which become deadly when mixed with Magnetize. Shields of allies touched by the pulse are restored.",
			CardImage = "PolarizeModx256.png",
			DarkIcon = "Polarize130xDark.png",
			WhiteIcon = "Polarize130xWhite.png",
			Warframe = "Mag",
		},
		["Crush"] = {
			Cost = 100,
			Key = 4,
			Description = "Magnetizes the bones of nearby enemies, causing them to collapse upon themselves.",
			CardImage = "CrushModx256.png",
			DarkIcon = "Crush130xDark.png",
			WhiteIcon = "Crush130xWhite.png",
			Warframe = "Mag",
		},
	--Mesa
		["Ballistic Battery"] = {
			Cost = 25,
			Key = 1,
			Description = "When activated, this power stores damage caused by guns. When triggered again, that damage is channeled through the next gunshot.",
			CardImage = "BallisticBatteryModx256.png",
			DarkIcon = "BallisticBattery130xDark.png",
			WhiteIcon = "BallisticBattery130xWhite.png",
			Warframe = "Mesa",
		},
		["Shooting Gallery"] = {
			Cost = 50,
			Key = 2,
			Description = "Gives an ally extra damage while jamming the guns of nearby enemies. This power shifts between team members.",
			CardImage = "ShootingGalleryModx256.png",
			DarkIcon = "ShootingGallery130xDark.png",
			WhiteIcon = "ShootingGallery130xWhite.png",
			Warframe = "Mesa",
		},
		["Shatter Shield"] = {
			Cost = 75,
			Key = 3,
			Description = "Envelops Mesa in a barrier of energy, reflecting back incoming bullet damage.",
			CardImage = "ShatterShieldModx256.png",
			DarkIcon = "ShatterShield130xDark.png",
			WhiteIcon = "ShatterShield130xWhite.png",
			Warframe = "Mesa",
		},
		["Peacemaker"] = {
			Cost = 25,
			Key = 4,
			Description = "With intense focus, Mesa draws her Regulator pistols, shooting down her foes in rapid succession.",
			CardImage = "PeacemakerModx256.png",
			DarkIcon = "Peacemaker130xDark.png",
			WhiteIcon = "Peacemaker130xWhite.png",
			Warframe = "Mesa",
		},
	--Mirage
		["Hall Of Mirrors"] = {
			Cost = 25,
			Key = 1,
			Description = "Mirage creates an entourage of doppelgangers to confuse and distract the enemy.",
			CardImage = "HallOfMirrorsModx256.png",
			DarkIcon = "HallOfMirrors130xDark.png",
			WhiteIcon = "HallOfMirrors130xWhite.png",
			Warframe = "Mirage",
		},
		["Sleight Of Hand"] = {
			Cost = 50,
			Key = 2,
			Description = "Booby trap nearby objects while conjuring an irresistible jewel that bursts with radial blind when touched in darkness, or a radial explosion in light. Conjure multiple smaller jewels with the help of Hall of Mirrors.",
			CardImage = "SleightOfHandModx256.png",
			DarkIcon = "SleightOfHand130xDark.png",
			WhiteIcon = "SleightOfHand130xWhite.png",
			Warframe = "Mirage",
		},
		["Eclipse"] = {
			Cost = 25,
			Key = 3,
			Description = "Standing in light, Mirage deals heavy damage, while the shadows make Mirage difficult to track and even harder to hurt.",
			CardImage = "EclipseModx256.png",
			DarkIcon = "Eclipse130xDark.png",
			WhiteIcon = "Eclipse130xWhite.png",
			Warframe = "Mirage",
		},
		["Prism"] = {
			Cost = 50,
			Key = 4,
			Description = "Fires an energy prism that shoots lasers in all directions. Activating again detonates the prism, blinding nearby foes.",
			CardImage = "PrismModx256.png",
			DarkIcon = "Prism130xDark.png",
			WhiteIcon = "Prism130xWhite.png",
			Warframe = "Mirage",
		},
	--Nekros
		["Soul Punch"] = {
			Cost = 25,
			Key = 1,
			Description = "A blow so powerful, it turns the enemy's very soul into a deadly projectile, damaging all in its path.",
			CardImage = "SoulPunchModx256.png",
			DarkIcon = "SoulPunch130xDark.png",
			WhiteIcon = "SoulPunch130xWhite.png",
			Warframe = "Nekros",
		},
		["Terrify"] = {
			Cost = 75,
			Key = 2,
			Description = "Casts fear into the hearts of nearby enemies, causing them to run away in terror.",
			CardImage = "TerrifyModx256.png",
			DarkIcon = "Terrify130xDark.png",
			WhiteIcon = "Terrify130xWhite.png",
			Warframe = "Nekros",
		},
		["Desecrate"] = {
			Cost = 10,
			Key = 3,
			Description = "Forces fallen enemies around you to drop additional loot.",
			CardImage = "DesecrateModx256.png",
			DarkIcon = "Desecrate130xDark.png",
			WhiteIcon = "Desecrate130xWhite.png",
			Warframe = "Nekros",
		},
		["Shadows Of The Dead"] = {
			Cost = 100,
			Key = 4,
			Description = "Summons shadow versions of vanquished enemies to fight alongside you for a short period of time.",
			CardImage = "ShadowsOfTheDeadModx256.png",
			DarkIcon = "ShadowsOfTheDead130xDark.png",
			WhiteIcon = "ShadowsOfTheDead130xWhite.png",
			Warframe = "Nekros",
		},
	--Nezha
		["Fire Walker"] = {
			Cost = 25,
			Key = 1,
			Description = "Blaze a trail of flames, scorching enemies and cleansing allies.",
			CardImage = "FireWalkerModx256.png",
			DarkIcon = "FireWalker130xDark.png",
			WhiteIcon = "FireWalker130xWhite.png",
			Warframe = "Nezha",
		},
		["Blazing Chakram"] = {
			Cost = 25,
			Key = 2,
			Description = "Hurl a flaming ring that burns enemies and causes them to emit a healing blast on death. Reactivate to instantly travel to the ring's location.",
			CardImage = "BlazingChakramModx256.png",
			DarkIcon = "BlazingChakram130xDark.png",
			WhiteIcon = "BlazingChakram130xWhite.png",
			Warframe = "Nezha",
		},
		["Warding Halo"] = {
			Cost = 75,
			Key = 3,
			Description = "Create a protective ring of fire that also stuns and damage enemies who get too close.",
			CardImage = "WardingHaloModx256.png",
			DarkIcon = "WardingHalo130xDark.png",
			WhiteIcon = "WardingHalo130xWhite.png",
			Warframe = "Nezha",
		},
		["Divine Spears"] = {
			Cost = 100,
			Key = 4,
			Description = "Impale nearby enemies on spears that erupt from the ground.",
			CardImage = "DivineSpearsModx256.png",
			DarkIcon = "DivineSpears130xDark.png",
			WhiteIcon = "DivineSpears130xWhite.png",
			Warframe = "Nezha",
		},
	--Nidus
		["Virulence"] = {
			Cost = 40,
			Key = 1,
			Description = "Rupture the ground with a damaging fungal growth that steals energy from each enemy it strikes. For every five enemies hit, the Infestation mutates, multiplying its destructive force.",
			CardImage = "VirulenceModx256.png",
			DarkIcon = "Virulence130xDark.png",
			WhiteIcon = "Virulence130xWhite.png",
			Warframe = "Nidus",
		},
		["Larva"] = {
			Cost = 25,
			Key = 2,
			Description = "Spawn an Infested pod that erupts with tendrils, latches onto nearby enemies and pulls them in.",
			CardImage = "LarvaModx256.png",
			DarkIcon = "Larva130xDark.png",
			WhiteIcon = "Larva130xWhite.png",
			Warframe = "Nidus",
		},
		["Parasitic Link"] = {
			Cost = 0,
			Key = 3,
			Description = "Bind to a target with a parasitic link. For allies, both the host and Nidus gain increased Ability Strength. Linked enemies take the damage inflicted on Nidus.",
			CardImage = "ParasiticLinkModx256.png",
			DarkIcon = "ParasiticLink130xDark.png",
			WhiteIcon = "ParasiticLink130xWhite.png",
			Warframe = "Nidus",
		},
		["Ravenous"] = {
			Cost = 0,
			Key = 4,
			Description = "Gluttonous maggots swarm nearby enemies, feasting until they burst with Infestation. The maggots benefit from Mutation and each enemy consumed adds to the Mutation stack.",
			CardImage = "RavenousModx256.png",
			DarkIcon = "Ravenous130xDark.png",
			WhiteIcon = "Ravenous130xWhite.png",
			Warframe = "Nidus",
		},
	--Nova
		["Null Star"] = {
			Cost = 25,
			Key = 1,
			Description = "Creates anti-matter particles that orbit Nova and seek nearby targets.",
			CardImage = "NullStarModx256.png",
			DarkIcon = "NullStar130xDark.png",
			WhiteIcon = "NullStar130xWhite.png",
			Warframe = "Nova",
		},
		["Antimatter Drop"] = {
			Cost = 50,
			Key = 2,
			Description = "Launches a contained particle of antimatter that will detonate upon collision.",
			CardImage = "AntimatterDropModx256.png",
			DarkIcon = "AntimatterDrop130xDark.png",
			WhiteIcon = "AntimatterDrop130xWhite.png",
			Warframe = "Nova",
		},
		["Worm Hole"] = {
			Cost = 75,
			Key = 3,
			Description = "Creates a wormhole allowing instantaneous travel.",
			CardImage = "WormHoleModx256.png",
			DarkIcon = "WormHole130xDark.png",
			WhiteIcon = "WormHole130xWhite.png",
			Warframe = "Nova",
		},
		["Molecular Prime"] = {
			Cost = 100,
			Key = 4,
			Description = "Primes all enemies in a radius with anti-matter.",
			CardImage = "MolecularPrimeModx256.png",
			DarkIcon = "MolecularPrime130xDark.png",
			WhiteIcon = "MolecularPrime130xWhite.png",
			Warframe = "Nova",
		},
	--Nyx
		["Mind Control"] = {
			Cost = 25,
			Key = 1,
			Description = "Nyx invades the psyche of a target, confusing enemies and making them fight for the Tenno cause.",
			CardImage = "MindControlModx256.png",
			DarkIcon = "MindControl130xDark.png",
			WhiteIcon = "MindControl130xWhite.png",
			Warframe = "Nyx",
		},
		["Psychic Bolts"] = {
			Cost = 50,
			Key = 2,
			Description = "Nyx launches a cluster of force bolts at enemies, using telekinesis to adjust flight paths and seek nearby targets.",
			CardImage = "PsychicBoltsModx256.png",
			DarkIcon = "PsychicBolts130xDark.png",
			WhiteIcon = "PsychicBolts130xWhite.png",
			Warframe = "Nyx",
		},
		["Chaos"] = {
			Cost = 75,
			Key = 3,
			Description = "With a powerful psychic blast, Nyx causes mass hysteria on the battlefield by confusing all enemies to attack random factions.",
			CardImage = "ChaosModx256.png",
			DarkIcon = "Chaos130xDark.png",
			WhiteIcon = "Chaos130xWhite.png",
			Warframe = "Nyx",
		},
		["Absorb"] = {
			Cost = 25,
			Key = 4,
			Description = "Nyx absorbs all incoming damage and channels that collected energy into an explosive radial discharge.",
			CardImage = "AbsorbModx256.png",
			DarkIcon = "Absorb130xDark.png",
			WhiteIcon = "Absorb130xWhite.png",
			Warframe = "Nyx",
		},
	--Oberon
		["Smite"] = {
			Cost = 25,
			Key = 1,
			Description = "Focuses deadly energy within a target and then projects it outwards, damaging both the target and surrounding enemies.",
			CardImage = "SmiteModx256.png",
			DarkIcon = "Smite130xDark.png",
			WhiteIcon = "Smite130xWhite.png",
			Warframe = "Oberon",
		},
		["Hallowed Ground"] = {
			Cost = 50,
			Key = 2,
			Description = "Sanctifies the ground before Oberon with righteous fire, inflicting damage to any enemy that stands in the flames.",
			CardImage = "HallowedGroundModx256.png",
			DarkIcon = "HallowedGround130xDark.png",
			WhiteIcon = "HallowedGround130xWhite.png",
			Warframe = "Oberon",
		},
		["Renewal"] = {
			Cost = 25,
			Key = 3,
			Description = "Healing waves of energy flow outward from Oberon to his allies, regenerating health over time.",
			CardImage = "RenewalModx256.png",
			DarkIcon = "Renewal130xDark.png",
			WhiteIcon = "Renewal130xWhite.png",
			Warframe = "Oberon",
		},
		["Reckoning"] = {
			Cost = 100,
			Key = 4,
			Description = "Quickly lifts enemies into the air and then hurls them down with conviction. Enemies who succumb to this power have a chance to spawn a Health Sphere.",
			CardImage = "ReckoningModx256.png",
			DarkIcon = "Reckoning130xDark.png",
			WhiteIcon = "Reckoning130xWhite.png",
			Warframe = "Oberon",
		},
	--Octavia
		["Mallet"] = {
			Cost = 25,
			Key = 1,
			Description = "Rhythmically beats damage into nearby enemies and draws their fire. Damage inflicted on the Mallet increases its lethality.",
			CardImage = "MalletModx256.png",
			DarkIcon = "Mallet130xDark.png",
			WhiteIcon = "Mallet130xWhite.png",
			Warframe = "Octavia",
		},
		["Resonator"] = {
			Cost = 50,
			Key = 2,
			Description = "Launches a rollerball that charms foes to follow it. Combines with the Mallet to create a roving ball of sonic destruction.",
			CardImage = "ResonatorModx256.png",
			DarkIcon = "Resonator130xDark.png",
			WhiteIcon = "Resonator130xWhite.png",
			Warframe = "Octavia",
		},
		["Metronome"] = {
			Cost = 75,
			Key = 3,
			Description = "Grants buffs to those who consistently perform actions in time to Octavia’s music. Timed jumps offer the Vivace speed buff. Crouching on the beat grants cloaking with the Nocturne buff. Firing rhythmically bestows Opera multishot buff. Timed melee swings give the Forte damage buff.",
			CardImage = "MetronomeModx256.png",
			DarkIcon = "Metronome130xDark.png",
			WhiteIcon = "Metronome130xWhite.png",
			Warframe = "Octavia",
		},
		["Amp"] = {
			Cost = 100,
			Key = 4,
			Description = "Draws power from the decibel level of sound in the area and uses it to amplify a damage buff for Octavia and her allies. It also doubles the damage and range of nearby Mallets.",
			CardImage = "AmpModx256.png",
			DarkIcon = "Amp130xDark.png",
			WhiteIcon = "Amp130xWhite.png",
			Warframe = "Octavia",
			Link = "Amp (Ability)",
		},
	--Revenant
		["Enthrall"] = {
			Cost = 25,
			Key = 1,
			Description = "Convert a target into a zealous thrall. Thralls turn on their allies and enthrall through damage. On death, they disintegrate into a damaging pillar of energy. The thrall horde remains under Revenant’s spell until this Ability runs out.",
			CardImage = "EnthrallModx256.png",
			DarkIcon = "Enthrall130xDark.png",
			WhiteIcon = "Enthrall130xWhite.png",
			Warframe = "Revenant",
		},
		["Mesmer Skin"] = {
			Cost = 50,
			Key = 2,
			Description = "Become enveloped in Sentient energy, which redirects damage and stuns all those who dare attack. Stunned enemies can be Enthralled at no energy cost.",
			CardImage = "MesmerSkinModx256.png",
			DarkIcon = "MesmerSkin130xDark.png",
			WhiteIcon = "MesmerSkin130xWhite.png",
			Warframe = "Revenant",
		},
		["Reave"] = {
			Cost = 50,
			Key = 3,
			Description = "Dash through enemies as a wall of Sentient energy, leeching shields and health from any encountered, enhanced for thralls.",
			CardImage = "ReaveModx256.png",
			DarkIcon = "Reave130xDark.png",
			WhiteIcon = "Reave130xWhite.png",
			Warframe = "Revenant",
		},
		["Danse Macabre"] = {
			Cost = 25,
			Key = 4,
			Description = "Erupt with a multitude of Eidolon energy beams and sweep a circle of death around Revenant. The beams will modify their Damage Type to target select defenses, while incoming damage is redirected back into the beams. Hold fire to boost Status Effects and Damage, at the cost of increased energy consumption. Thralls killed by this leave overshield pickups. ",
			CardImage = "DanseMacabreModx256.png",
			DarkIcon = "DanseMacabre130xDark.png",
			WhiteIcon = "DanseMacabre130xWhite.png",
			Warframe = "Revenant",
		},
	--Rhino
		["Rhino Charge"] = {
			Cost = 25,
			Key = 1,
			Description = "Rhino charges towards a target, clobbering any in his path and goring his victim.",
			CardImage = "RhinoChargeModx256.png",
			DarkIcon = "RhinoCharge130xDark.png",
			WhiteIcon = "RhinoCharge130xWhite.png",
			Warframe = "Rhino",
		},
		["Iron Skin"] = {
			Cost = 50,
			Key = 2,
			Description = "Rhino hardens his skin, insulating himself from all damage.",
			CardImage = "IronSkinModx256.png",
			DarkIcon = "IronSkin130xDark.png",
			WhiteIcon = "IronSkin130xWhite.png",
			Warframe = "Rhino",
		},
		["Roar"] = {
			Cost = 75,
			Key = 3,
			Description = "Grants all nearby Warframes increased damage for a short duration.",
			CardImage = "RoarModx256.png",
			DarkIcon = "Roar130xDark.png",
			WhiteIcon = "Roar130xWhite.png",
			Warframe = "Rhino",
		},
		["Rhino Stomp"] = {
			Cost = 100,
			Key = 4,
			Description = "Rhino stomps with force sufficient to disrupt time, tumbling enemies around him in stasis.",
			CardImage = "RhinoStompModx256.png",
			DarkIcon = "RhinoStomp130xDark.png",
			WhiteIcon = "RhinoStomp130xWhite.png",
			Warframe = "Rhino",
		},
	--Saryn
		["Spores"] = {
			Cost = 25,
			Key = 1,
			Description = "Inflict a target with a pox of Corrosive spores. Spread spores to nearby enemies by destroying them or killing their host. The longer the Spore spreads, its damage will increase.",
			CardImage = "SporesModx256.png",
			DarkIcon = "Spores130xDark.png",
			WhiteIcon = "Spores130xWhite.png",
			Warframe = "Saryn",
		},
		["Molt"] = {
			Cost = 50,
			Key = 2,
			Description = "Shedding her skin like a snake, Saryn leaves a decoy behind to draw fire from enemies.",
			CardImage = "MoltModx256.png",
			DarkIcon = "Molt130xDark.png",
			WhiteIcon = "Molt130xWhite.png",
			Warframe = "Saryn",
		},
		["Toxic Lash"] = {
			Cost = 50,
			Key = 3,
			Description = "While active, attacks deal additional Toxin damage; this effect is doubled for melee strikes. Instantly burst spores when attacking afflicted enemies.",
			CardImage = "ToxicLashModx256.png",
			DarkIcon = "ToxicLash130xDark.png",
			WhiteIcon = "ToxicLash130xWhite.png",
			Warframe = "Saryn",
		},
		["Miasma"] = {
			Cost = 75,
			Key = 4,
			Description = "Releases a poisonous miasma that deals Viral damage to enemies in range. Foes afflicted by spores are more susceptible to the mist.",
			CardImage = "MiasmaModx256.png",
			DarkIcon = "Miasma130xDark.png",
			WhiteIcon = "Miasma130xWhite.png",
			Warframe = "Saryn",
		},
	--Titania
		["Spellbind"] = {
			Cost = 25,
			Key = 1,
			Description = "Enemies fumble their weapons as they tumble into the air. Nearby allies become immune to Status Effects.",
			CardImage = "SpellbindModx256.png",
			DarkIcon = "Spellbind130xDark.png",
			WhiteIcon = "Spellbind130xWhite.png",
			Warframe = "Titania",
		},
		["Tribute"] = {
			Cost = 50,
			Key = 2,
			Description = "Extract an offering from an enemy in the form of a random Ability Buff. Survivor's attacks are weakened.",
			CardImage = "TributeModx256.png",
			DarkIcon = "Tribute130xDark.png",
			WhiteIcon = "Tribute130xWhite.png",
			Warframe = "Titania",
		},
		["Lantern"] = {
			Cost = 75,
			Key = 3,
			Description = "Create a swarm of razorflies that transform an enemy into an irresistible floating beacon, attracting witless comrades and finally exploding.",
			CardImage = "LanternModx256.png",
			DarkIcon = "Lantern130xDark.png",
			WhiteIcon = "Lantern130xWhite.png",
			Warframe = "Titania",
		},
		["Razorwing"] = {
			Cost = 25,
			Key = 4,
			Description = "Shrink down and take flight, while razorflies attack nearby enemies.",
			CardImage = "RazorwingModx256.png",
			DarkIcon = "Razorwing130xDark.png",
			WhiteIcon = "Razorwing130xWhite.png",
			Warframe = "Titania",
		},
	--Trinity
		["Well Of Life"] = {
			Cost = 25,
			Key = 1,
			Description = "Create a well of life on an enemy. Allies will gain health when damaging the target.",
			CardImage = "WellOfLifeModx256.png",
			DarkIcon = "WellOfLife130xDark.png",
			WhiteIcon = "WellOfLife130xWhite.png",
			Warframe = "Trinity",
		},
		["Energy Vampire"] = {
			Cost = 50,
			Key = 2,
			Description = "Allies will gain energy over time when enemies are marked with Energy Vampire.",
			CardImage = "EnergyVampireModx256.png",
			DarkIcon = "EnergyVampire130xDark.png",
			WhiteIcon = "EnergyVampire130xWhite.png",
			Warframe = "Trinity",
		},
		["Link"] = {
			Cost = 75,
			Key = 3,
			Description = "Any damage taken while Link is active will be channeled to a nearby enemy.",
			CardImage = "LinkModx256.png",
			DarkIcon = "Link130xDark.png",
			WhiteIcon = "Link130xWhite.png",
			Warframe = "Trinity",
		},
		["Blessing"] = {
			Cost = 100,
			Key = 4,
			Description = "Restore the health and shields of allies within Trinity's Affinity aura while giving them some damage immunity.",
			CardImage = "BlessingModx256.png",
			DarkIcon = "Blessing130xDark.png",
			WhiteIcon = "Blessing130xWhite.png",
			Warframe = "Trinity",
		},
	--Valkyr
		["Rip Line"] = {
			Cost = 25,
			Key = 1,
			Description = "Valkyr hurls forth a hook. If it hits an enemy, she pulls them to her. If it hits terrain, she pulls herself to the hook's location.",
			CardImage = "RipLineModx256.png",
			DarkIcon = "RipLine130xDark.png",
			WhiteIcon = "RipLine130xWhite.png",
			Warframe = "Valkyr",
		},
		["Warcry"] = {
			Cost = 75,
			Key = 2,
			Description = "Valkyr lets out a rallying cry that bolsters her allies melee speed while slowing down nearby enemies.",
			CardImage = "WarcryModx256.png",
			DarkIcon = "Warcry130xDark.png",
			WhiteIcon = "Warcry130xWhite.png",
			Warframe = "Valkyr",
		},
		["Paralysis"] = {
			Cost = 5,
			Key = 3,
			Description = "Valkyr unleashes her shields, stunning and damaging enemies around her.",
			CardImage = "ParalysisModx256.png",
			DarkIcon = "Paralysis130xDark.png",
			WhiteIcon = "Paralysis130xWhite.png",
			Warframe = "Valkyr",
		},
		["Hysteria"] = {
			Cost = 25,
			Key = 4,
			Description = "Valkyr is imbued with energy and becomes a ball of vicious rage, capable of unleashing a torrent of deadly claw attacks on unsuspecting foes.",
			CardImage = "HysteriaModx256.png",
			DarkIcon = "Hysteria130xDark.png",
			WhiteIcon = "Hysteria130xWhite.png",
			Warframe = "Valkyr",
		},
	--Vauban
		["Tesla"] = {
			Cost = 25,
			Key = 1,
			Description = "Launches a grenade that holds an electrical charge, zapping enemies that come within range.",
			CardImage = "TeslaModx256.png",
			DarkIcon = "Tesla130xDark.png",
			WhiteIcon = "Tesla130xWhite.png",
			Warframe = "Vauban",
		},
		["Minelayer"] = {
			Cost = 50,
			Key = 2,
			Description = "Cycle through four deployable trap mines: Bounce, Trip Laser, Shred and Concuss.",
			CardImage = "MinelayerModx256.png",
			DarkIcon = "Minelayer130xDark.png",
			WhiteIcon = "Minelayer130xWhite.png",
			Warframe = "Vauban",
		},
		["Bastille"] = {
			Cost = 75,
			Key = 3,
			Description = "Creates an energy-based containment field in which captives are held suspended in stasis.",
			CardImage = "BastilleModx256.png",
			DarkIcon = "Bastille130xDark.png",
			WhiteIcon = "Bastille130xWhite.png",
			Warframe = "Vauban",
		},
		["Vortex"] = {
			Cost = 100,
			Key = 4,
			Description = "Creates a whirling mass of energy that violently attracts nearby enemies, crushing their atoms into a tiny spec of matter.",
			CardImage = "VortexModx256.png",
			DarkIcon = "Vortex130xDark.png",
			WhiteIcon = "Vortex130xWhite.png",
			Warframe = "Vauban",
		},
	--Volt
		["Shock"] = {
			Cost = 25,
			Key = 1,
			Description = "Launches a shocking projectile. It stuns and deals high damage to a single target and chains damage to nearby enemies.",
			CardImage = "ShockModx256.png",
			DarkIcon = "Shock130xDark.png",
			WhiteIcon = "Shock130xWhite.png",
			Warframe = "Volt",
		},
		["Speed"] = {
			Cost = 25,
			Key = 2,
			Description = "Volt energizes his body and nearby Warframes, giving them increased speed and dexterity for a short time.",
			CardImage = "SpeedModx256.png",
			DarkIcon = "Speed130xDark.png",
			WhiteIcon = "Speed130xWhite.png",
			Warframe = "Volt",
		},
		["Electric Shield"] = {
			Cost = 50,
			Key = 3,
			Description = "Volt deploys an obstacle of energy, providing cover in any situation.",
			CardImage = "ElectricShieldModx256.png",
			DarkIcon = "ElectricShield130xDark.png",
			WhiteIcon = "ElectricShield130xWhite.png",
			Warframe = "Volt",
		},
		["Discharge"] = {
			Cost = 100,
			Key = 4,
			Description = "Paralyze nearby hostiles with a damaging electric charge, this also shocks approaching enemies.",
			CardImage = "DischargeModx256.png",
			DarkIcon = "Discharge130xDark.png",
			WhiteIcon = "Discharge130xWhite.png",
			Warframe = "Volt",
		},
	--Wukong
		["Iron Jab"] = {
			Cost = 25,
			Key = 1,
			Description = "Explode the Iron Staff to its true length, knocking down anything in its path.",
			CardImage = "IronJabModx256.png",
			DarkIcon = "IronJab130xDark.png",
			WhiteIcon = "IronJab130xWhite.png",
			Warframe = "Wukong",
		},
		["Defy"] = {
			Cost = 50,
			Key = 2,
			Description = "Escape death by receiving a boost of health when killed.",
			CardImage = "DefyModx256.png",
			DarkIcon = "Defy130xDark.png",
			WhiteIcon = "Defy130xWhite.png",
			Warframe = "Wukong",
		},
		["Cloud Walker"] = {
			Cost = 25,
			Key = 3,
			Description = "Evaporate into a cloud of mist and float through the battlefield.",
			CardImage = "CloudWalkerModx256.png",
			DarkIcon = "CloudWalker130xDark.png",
			WhiteIcon = "CloudWalker130xWhite.png",
			Warframe = "Wukong",
		},
		["Primal Fury"] = {
			Cost = 25,
			Key = 4,
			Description = "Summon the Iron Staff and unleash fury.",
			CardImage = "PrimalFuryModx256.png",
			DarkIcon = "PrimalFury130xDark.png",
			WhiteIcon = "PrimalFury130xWhite.png",
			Warframe = "Wukong",
		},
	--Zephyr
		["Tail Wind"] = {
			Cost = 25,
			Key = 1,
			Description = "From the ground, charge and release to launch Zephyr into an airborne hover. From the air, tap to dash forward, or aim down to dive bomb enemies below.",
			CardImage = "TailWindModx256.png",
			DarkIcon = "TailWind130xDark.png",
			WhiteIcon = "TailWind130xWhite.png",
			Warframe = "Zephyr",
		},
		["Airburst"] = {
			Cost = 50,
			Key = 2,
			Description = "Generate a burst of massively dense air that explodes on contact and sends enemies flying. Launch Airbursts into Tornadoes to make them grow.",
			CardImage = "AirburstModx256.png",
			DarkIcon = "Airburst130xDark.png",
			WhiteIcon = "Airburst130xWhite.png",
			Warframe = "Zephyr",
		},
		["Turbulence"] = {
			Cost = 75,
			Key = 3,
			Description = "Creates a wind shield around Zephyr, redirecting all incoming projectiles.",
			CardImage = "TurbulenceModx256.png",
			DarkIcon = "Turbulence130xDark.png",
			WhiteIcon = "Turbulence130xWhite.png",
			Warframe = "Zephyr",
		},
		["Tornado"] = {
			Cost = 100,
			Key = 4,
			Description = "Create deadly tornadoes that seek out and engulf enemies. Tornadoes deal the elemental damage type they absorb the most. Shoot enemies engulfed in Tornadoes to do additional damage.",
			CardImage = "TornadoModx256.png",
			DarkIcon = "Tornado130xDark.png",
			WhiteIcon = "Tornado130xWhite.png",
			Warframe = "Zephyr",
		},
	},
	["Warframe"] = {
		["Ash"] = {"Shuriken","Smoke Screen","Teleport","Blade Storm"},
		["Atlas"] = {"Landslide","Tectonics","Petrify","Rumblers"},
		["Banshee"] = {"Sonic Boom","Sonar","Silence","Sound Quake"},
		["Baruuk"] = {"Elude","Lull","Desolate Hands","Serene Storm"},
		["Chroma"] = {"Spectral Scream","Elemental Ward","Vex Armor","Effigy"},
		["Ember"] = {"Fireball","Accelerant","Fire Blast","World On Fire"},
		["Equinox"] = {"Metamorphosis","Rest & Rage","Pacify & Provoke","Mend & Maim"},
		["Excalibur"] = {"Slash Dash","Radial Blind","Radial Javelin","Exalted Blade"},
		["Excalibur Umbra"] = {"Slash Dash","Radial Howl","Radial Javelin","Exalted Blade"},
		["Frost"] = {"Freeze","Ice Wave","Snow Globe","Avalanche"},
		["Gara"] = {"Shattered Lash","Splinter Storm","Spectrorage","Mass Vitrify"},
		["Garuda"] = {"Dread Mirror","Blood Altar","Bloodletting","Seeking Talons"},
		["Harrow"] = {"Condemn","Penance","Thurible","Covenant"},
		["Hydroid"] = {"Tempest Barrage","Tidal Surge","Undertow","Tentacle Swarm"},
		["Inaros"] = {"Desiccation","Devour","Sandstorm","Scarab Swarm"},
		["Ivara"] = {"Quiver","Navigator","Prowl","Artemis Bow"},
		["Khora"] = {"Whipclaw","Ensnare","Venari","Strangledome"},
		["Limbo"] = {"Banish","Stasis","Rift Surge","Cataclysm"},
		["Loki"] = {"Decoy","Invisibility","Switch Teleport","Radial Disarm"},
		["Mag"] = {"Pull","Magnetize","Polarize","Crush"},
		["Mesa"] = {"Ballistic Battery","Shooting Gallery","Shatter Shield","Peacemaker"},
		["Mirage"] = {"Hall Of Mirrors","Sleight Of Hand","Eclipse","Prism"},
		["Nekros"] = {"Soul Punch","Terrify","Desecrate","Shadows Of The Dead"},
		["Nezha"] = {"Fire Walker","Blazing Chakram","Warding Halo","Divine Spears"},
		["Nidus"] = {"Virulence","Larva","Parasitic Link","Ravenous"},
		["Nova"] = {"Null Star","Antimatter Drop","Worm Hole","Molecular Prime"},
		["Nyx"] = {"Mind Control","Psychic Bolts","Chaos","Absorb"},
		["Oberon"] = {"Smite","Hallowed Ground","Renewal","Reckoning"},
		["Octavia"] = {"Mallet","Resonator","Metronome","Amp"},
		["Revenant"] = {"Enthrall","Mesmer Skin","Reave","Danse Macabre"},
		["Rhino"] = {"Rhino Charge","Iron Skin","Roar","Rhino Stomp"},
		["Saryn"] = {"Spores","Molt","Toxic Lash","Miasma"},
		["Titania"] = {"Spellbind","Tribute","Lantern","Razorwing"},
		["Trinity"] = {"Well Of Life","Energy Vampire","Link","Blessing"},
		["Valkyr"] = {"Rip Line","Warcry","Paralysis","Hysteria"},
		["Vauban"] = {"Tesla","Minelayer","Bastille","Vortex"},
		["Volt"] = {"Shock","Speed","Electric Shield","Discharge"},
		["Wukong"] = {"Iron Jab","Defy","Cloud Walker","Primal Fury"},
		["Zephyr"] = {"Tail Wind","Airburst","Turbulence","Tornado"},
	},
}

return AbilityData