-- 注意！这个页面的内容不要直接用英文维基上的内容整页覆盖（一些图片的使用有出入）。
--Last Updated 18/12/18

local WarframeData = {
    ["IgnoreInCount"] = {"Excalibur Umbra Prime"},
    ["Warframes"] = {
        ["Ash"] = {
            Armor = 65,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 100,
            Health = 150,
            Image = "AshNewLook.png",
            Portrait = "AshIcon272.png",
            Name = "Ash",
            Polarities = {"V", "V"},
            Shield = 100,
            Sprint = 1.15,
            Introduced = "Vanilla",
            Sex = "Male",
            MainCost = {
                Credits = 25000,
                BPCost = 35000,
                MarketCost = 375,
                Rush = 50,
                Time = 72,
                Parts = {
                    { Name = "Neuroptics",Type = "Item",Count = 1,},
                    { Name = "Chassis",Type = "Item",Count = 1,},
                    { Name = "Systems",Type = "Item",Count = 1,},
                    { Name = "Orokin Cell",Type = "Resource",Count = 1,},},
            },
            NeuroCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Alloy Plate",Type = "Resource",Count = 150,},
                    { Name = "Neural Sensors",Type = "Resource",Count = 1,},
                    { Name = "Polymer Bundle",Type = "Resource",Count = 150,},
                    { Name = "Rubedo",Type = "Resource",Count = 500,},},
            },
            ChassisCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Morphics",Type = "Resource",Count = 1,},
                    { Name = "Ferrite",Type = "Resource",Count = 1000,},
                    { Name = "Rubedo",Type = "Resource",Count = 300,},},
            },
            SystemCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Control Module",Type = "Resource",Count = 1,},
                    { Name = "Morphics",Type = "Resource",Count = 1,},
                    { Name = "Salvage",Type = "Resource",Count = 500,},
                    { Name = "Plastids",Type = "Resource",Count = 500,},},
            },
        },
        ["Ash Prime"] = {
            Armor = 150,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 100,
            Health = 150,
            Image = "AshPrimeNewLook.png",
            Portrait = "Ash PrimeIcon272.png",
            Name = "Ash Prime",
            Polarities = {"Bar", "V", "V"},
            Shield = 125,
            Sprint = 1.2,
            Introduced = "16.11",
            Sex = "Male",
            Vaulted = true,
            MainCost = {
                Credits = 25000,
                Rush = 50,
                Time = 72,
                Parts = {
                    { Name = "Prime Neuroptics",Type = "Item",Count = 1,},
                    { Name = "Prime Chassis",Type = "Item",Count = 1,},
                    { Name = "Prime Systems",Type = "Item",Count = 1,},
                    { Name = "Orokin Cell",Type = "Resource",Count = 1,},},
            },
            NeuroCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Alloy Plate",Type = "Resource",Count = 150,},
                    { Name = "Neural Sensors",Type = "Resource",Count = 2,},
                    { Name = "Slavage",Type = "Resource",Count = 1000,},
                    { Name = "Rubedo",Type = "Resource",Count = 750,},},
            },
            ChassisCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Gallium",Type = "Resource",Count = 3,},
                    { Name = "Nano Spores",Type = "Resource",Count = 1000,},
                    { Name = "Rubedo",Type = "Resource",Count = 400,},},
            },
            SystemCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Control Module",Type = "Resource",Count = 3,},
                    { Name = "Orokin Cell",Type = "Resource",Count = 1,},
                    { Name = "Ferrite",Type = "Resource",Count = 1000,},
                    { Name = "Circuits",Type = "Resource",Count = 500,},},
            },
        },
        ["Atlas"] = {
            Armor = 450,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 150,
            Health = 100,
            Image = "AtlasNewLook.png",
            Portrait = "AtlasIcon272.png",
            Name = "Atlas",
            Polarities = {"Bar", "D", "V"},
            Shield = 100,
            Sprint = 0.9,
            Introduced = "17.5",
            Sex = "Male",
            MainCost = {
                Credits = 30000,
                MarketCost = 275,
                Rush = 50,
                Time = 72,
                Parts = {
                    { Name = "Neuroptics",Type = "Item",Count = 1,},
                    { Name = "Chassis",Type = "Item",Count = 1,},
                    { Name = "Systems",Type = "Item",Count = 1,},
                    { Name = "Orokin Cell",Type = "Resource",Count = 1,},},
            },
            NeuroCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Polymer Bundle",Type = "Resource",Count = 1400,},
                    { Name = "Alloy Plate",Type = "Resource",Count = 1100,},
                    { Name = "Circuits",Type = "Resource",Count = 800,},
                    { Name = "Neurodes",Type = "Resource",Count = 5,},},
            },
            ChassisCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Nano Spores",Type = "Resource",Count = 1800,},
                    { Name = "Cryotic",Type = "Resource",Count = 1300,},
                    { Name = "Rubedo",Type = "Resource",Count = 700,},
                    { Name = "Argon Crystal",Type = "Resource",Count = 2},},
            },
            SystemCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Ferrite",Type = "Resource",Count = 4600,},
                    { Name = "Polymer Bundle",Type = "Resource",Count = 1700,},
                    { Name = "Morphics",Type = "Resource",Count = 5,},
                    { Name = "Orokin Cell",Type = "Resource",Count = 1,},},
            },
        },
        ["Banshee"] = {
            Armor = 15,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 150,
            Health = 100,
            Image = "BansheeNewLook.png",
            Portrait = "BansheeIcon272.png",
            Name = "Banshee",
            Polarities = {"V", "V"},
            Shield = 100,
            Sprint = 1.1,
            Introduced = "7",
            Sex = "Female",
            MainCost = {
                Credits = 25000,
                MarketCost = 225,
                Rush = 50,
                Time = 72,
                Parts = {
                    { Name = "Neuroptics",Type = "Item",Count = 1,},
                    { Name = "Chassis",Type = "Item",Count = 1,},
                    { Name = "Systems",Type = "Item",Count = 1,},
                    { Name = "Orokin Cell",Type = "Resource",Count = 1,},},
            },
            NeuroCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Circuits",Type = "Resource",Count = 150,},
                    { Name = "Neural Sensors",Type = "Resource",Count = 1,},
                    { Name = "Polymer Bundle",Type = "Resource",Count = 200,},
                    { Name = "Salvage",Type = "Resource",Count = 500,},},
            },
            ChassisCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Morphics",Type = "Resource",Count = 1,},
                    { Name = "Ferrite",Type = "Resource",Count = 900,},
                    { Name = "Rubedo",Type = "Resource",Count = 50,},},
            },
            SystemCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Control Module",Type = "Resource",Count = 1,},
                    { Name = "Morphics",Type = "Resource",Count = 1,},
                    { Name = "Salvage",Type = "Resource",Count = 500,},
                    { Name = "Plastids",Type = "Resource",Count = 400,},},
            },
        },
        ["Banshee Prime"] = {
            Armor = 65,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 175,
            Health = 100,
            Image = "BansheePrimeNewLook.png",
            Portrait = "Banshee PrimeIcon272.png",
            Mastery = 8,
            Name = "Banshee Prime",
            Polarities = {"V", "V", "Bar"},
            Shield = 100,
            Sprint = 1.15,
            Introduced = "19.11.5",
            Sex = "Female",
            Vaulted = true,
        },
        ["Baruuk"] = {
            Armor = 150,
            AuraPolarity = "Bar",
            Conclave = false,
            Energy = 200,
            ExilusPolarity = "Bar",
            Health = 75,
            Image = "BaruukNewLook.png",
            Portrait = "BaruukIcon272.png",
            Name = "Baruuk",
            Polarities = {"D", "D"},
            Shield = 100,
            Sprint = 1.20,
            Introduced = "24.2",
            Sex = "Male",
        },
        ["Chroma"] = {
            Armor = 350,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 150,
            Health = 100,
            Image = "ChromaNewLook.png",
            Portrait = "ChromaIcon272.png",
            Name = "Chroma",
            Polarities = {"Bar", "V"},
            Shield = 100,
            Sprint = 1,
            Introduced = "16",
            Sex = "Male",
        },
        ["Chroma Prime"] = {
            Armor = 425,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 200,
            Health = 100,
            Image = "ChromaPrimeNewLook.png",
            Portrait = "Chroma PrimeIcon272.png",
            Mastery = 6,
            Name = "Chroma Prime",
            Polarities = {"Bar", "D", "V", "Bar"},
            Shield = 100,
            Sprint = 1,
            Introduced = "23.9",
            Sex = "Male",
        },
        ["Ember"] = {
            Armor = 100,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 150,
            Health = 100,
            Image = "EmberNewLook.png",
            Portrait = "EmberIcon272.png",
            Name = "Ember",
            Polarities = {"Bar", "Bar"},
            Shield = 100,
            Sprint = 1.1,
            Introduced = "Vanilla",
            Sex = "Female",
        },
        ["Ember Prime"] = {
            Armor = 125,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 150,
            Health = 100,
            Image = "EmberPrimeNewLook.png",
            Portrait = "Ember PrimeIcon272.png",
            Name = "Ember Prime",
            Polarities = {"V", "D"},
            Shield = 125,
            Sprint = 1.1,
            Introduced = "11",
            Sex = "Female",
            Vaulted = true,
        },
        ["Equinox"] = {
            Armor = 100,
            AuraPolarity = "Bar",
            Conclave = true,
            Energy = 150,
            Health = 100,
            Name = "Equinox",
            Portrait = "EquinoxIcon272.png",
            Polarities = {"D", "V"},
            Shield = 100,
            Sprint = 1.15,
            Introduced = "17",
            Sex = "Female",
        },
        ["Excalibur"] = {
            Armor = 225,
            AuraPolarity = "None",
            Conclave = true,
            Energy = 100,
            Health = 100,
            Image = "ExcaliburNewLook.png",
            Portrait = "ExcaliburIcon272.png",
            Name = "Excalibur",
            Polarities = {"D", "V"},
            Shield = 100,
            Sprint = 1,
            Introduced = "Vanilla",
            Sex = "Male",
        },
        ["Excalibur Prime"] = {
            Armor = 300,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 150,
            Health = 100,
            Image = "ExcaliburPrimeNewLook.png",
            Portrait = "Excalibur PrimeIcon272.png",
            Name = "Excalibur Prime",
            Polarities = {"D", "V", "V"},
            Shield = 100,
            Sprint = 1,
            Introduced = "5",
            Sex = "Male",
            Vaulted = "N/A",
        },
        ["Excalibur Umbra"] = {
            Armor = 300,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 150,
            Health = 100,
            Image = "ExcaliburUmbraNewLook.png",
            Portrait = "Excalibur UmbraIcon272.png",
            Name = "Excalibur Umbra",
            Polarities = {"V", "U", "U", "U"},
            Shield = 100,
            Sprint = 1,
            Introduced = "23",
            Sex = "Male",
            Vaulted = "N/A",
        },
        ["Excalibur Umbra Prime"] = {
            Armor = 250,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 150,
            Health = 100,
            Image = "ExcaliburUmbraPrime.png",
            Name = "Excalibur Umbra Prime",
            Polarities = {"D", "V", "V"},
            Shield = 100,
            Sprint = 1,
            Sex = "Male",
            Vaulted = "N/A",
        },
        ["Frost"] = {
            Armor = 300,
            AuraPolarity = "D",
            Conclave = true,
            Energy = 100,
            Health = 100,
            Image = "FrostNewLook.png",
            Portrait = "FrostIcon272.png",
            Name = "Frost",
            Polarities = {"Bar", "D"},
            Shield = 150,
            Sprint = 0.95,
            Introduced = "6",
            Sex = "Male",
        },
        ["Frost Prime"] = {
            Armor = 300,
            AuraPolarity = "D",
            Conclave = true,
            Energy = 100,
            Health = 100,
            Image = "FrostPrimeNewLook.png",
            Portrait = "Frost PrimeIcon272.png",
            Name = "Frost Prime",
            Polarities = {"Bar", "D", "D"},
            Shield = 175,
            Sprint = 0.95,
            Introduced = "7.10",
            Sex = "Male",
            Vaulted = true,
        },
        ["Gara"] = {
            Armor = 125,
            AuraPolarity = "D",
            Conclave = true,
            Energy = 150,
            Health = 100,
            Image = "GaraNewLook.png",
            Portrait = "GaraIcon272.png",
            Name = "Gara",
            Polarities = {"V", "V"},
            Shield = 100,
            Sprint = 1.15,
            Introduced = "22",
            Sex = "Female",
        },
        ["Garuda"] = {
            Armor = 300,
            AuraPolarity = "V",
            Conclave = false,
            Energy = 120,
            EnergyRank30 = 270,
            Health = 100,
            Image = "GarudaNewLook.png",
            Portrait = "GarudaIcon272.png",
            Name = "Garuda",
            Polarities = {"Bar", "D"},
            Shield = 100,
            Sprint = 1.00,
            Introduced = "24",
            Sex = "Female",
        },
        ["Harrow"] = {
            Armor = 150,
            AuraPolarity = "Bar",
            Conclave = true,
            Energy = 100,
            Health = 100,
            Image = "Harrow.png",
            Portrait = "HarrowIcon272.png",
            Name = "Harrow",
            Polarities = {"D", "Bar"},
            Shield = 150,
            Sprint = 1,
            Introduced = "21",
            Sex = "Male",
        },
        ["Hydroid"] = {
            Armor = 200,
            AuraPolarity = "Bar",
            Conclave = true,
            Energy = 125,
            Health = 100,
            Image = "HydroidNewLook.png",
            Portrait = "HydroidIcon272.png",
            Name = "Hydroid",
            Polarities = {"V", "Bar"},
            Shield = 125,
            Sprint = 1.05,
            Introduced = "13",
            Sex = "Male",
        },
        ["Hydroid Prime"] = {
            Armor = 250,
            AuraPolarity = "Bar",
            Conclave = true,
            Energy = 150,
            Health = 100,
            Image = "HydroidPrimeNewLook.png",
            Portrait = "Hydroid PrimeIcon272.png",
        	Mastery = 5,
            Name = "Hydroid Prime",
            Polarities = {"V", "D", "Bar", "Bar"},
            Shield = 175,
            Sprint = 1.05,
            Introduced = "21.6",
            Sex = "Male",
            Vaulted = false,
        },
        ["Inaros"] = {
            Armor = 200,
            AuraPolarity = "Bar",
            Conclave = true,
            Energy = 100,
            ExilusPolarity = "Bar",
            Health = 550.0,
            HealthRank30 = 2200,
            Image = "InarosNewLook.png",
            Portrait = "InarosIcon272.png",
            Name = "Inaros",
            Polarities = {"D", "D"},
            Shield = 0,
            Sprint = 1,
            Introduced = "18.5",
            Sex = "Male",
        },
        ["Ivara"] = {
            Armor = 65,
            AuraPolarity = "Bar",
            Conclave = true,
            Energy = 175,
            Health = 75,
            Image = "IvaraNewLook.png",
            Portrait = "IvaraIcon272.png",
            Name = "Ivara",
            Polarities = {"D", "Bar"},
            Shield = 100,
            Sprint = 1.15,
            Introduced = "18",
            Sex = "Female"
        },
        ["Khora"] = {
            Armor = 275,
            AuraPolarity = "D",
            Conclave = true,
            ExilusPolarity = "Bar",
            Energy = 125,
            Health = 125,
            Image = "KhoraNewLook.png",
            Portrait = "KhoraIcon272.png",
            Name = "Khora",
            Polarities = {"V", "Bar"},
            Shield = 100,
            Sprint = 1.05,
            Introduced = "22.18.0",
            Sex = "Female"
        },
        ["Limbo"] = {
            Armor = 65,
            AuraPolarity = "Bar",
            Conclave = true,
            Energy = 150,
            Health = 100,
            Image = "LimboNewLook.png",
            Portrait = "LimboIcon272.png",
            Name = "Limbo",
            Polarities = {"V", "V"},
            Shield = 75,
            Sprint = 1.15,
            Introduced = "15",
            Sex = "Male",
        },
        ["Limbo Prime"] = {
            Mastery = 4,
            Armor = 85,
            AuraPolarity = "Bar",
            Conclave = true,
            Energy = 175,
            Health = 100,
            Image = "LimboPrimeNewLook.png",
            Portrait = "Limbo PrimeIcon272.png",
            Name = "Limbo Prime",
            Polarities = {"V", "V", "Bar", "D"},
            Shield = 100,
            Sprint = 1.15,
            Introduced = "23.0.3",
            Sex = "Male",
        },
        ["Loki"] = {
            Armor = 65,
            AuraPolarity = "Bar",
            Conclave = true,
            Energy = 150,
            Health = 75,
            Image = "LokiNewLook.png",
            Portrait = "LokiIcon272.png",
            Name = "Loki",
            Polarities = {"D", "V"},
            Shield = 75,
            Sprint = 1.25,
            Introduced = "Vanilla",
            Sex = "Male"
        },
        ["Loki Prime"] = {
            Armor = 65,
            AuraPolarity = "Bar",
            Conclave = true,
            Energy = 175,
            Health = 75,
            Image = "LokiPrimeNewLook.png",
            Portrait = "Loki PrimeIcon272.png",
            Name = "Loki Prime",
            Polarities = {"D", "D", "V", "Bar"},
            Shield = 75,
            Sprint = 1.25,
            Introduced = "13.7",
            Sex = "Male",
            Vaulted = true,
        },
        ["Mag"] = {
            Armor = 65,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 125,
            Health = 75,
            Image = "MagNewLook.png",
            Portrait = "MagIcon272.png",
            Name = "Mag",
            Polarities = {"Bar", "Bar"},
            Shield = 150,
            Sprint = 1,
            Introduced = "Vanilla",
            Sex = "Female"
        },
        ["Mag Prime"] = {
            Armor = 65,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 175,
            Health = 100,
            Image = "MagPrimeNewLook.png",
            Portrait = "Mag PrimeIcon272.png",
            Name = "Mag Prime",
            Polarities = {"Bar", "Bar", "V"},
            Shield = 150,
            Sprint = 1,
            Introduced = "10",
            Sex = "Female",
            Vaulted = false,
        },
        ["Mesa"] = {
            Armor = 65,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 100,
            Health = 125,
            Image = "MesaLarge.png",
            Portrait = "MesaIcon272.png",
            Name = "Mesa",
            Polarities = {"Bar", "Bar"},
            Shield = 75,
            Sprint = 1.1,
            Introduced = "15.5",
            Sex = "Female"
        },
        ["Mesa Prime"] = {
            Armor = 85,
            AuraPolarity = "V",
            Conclave = false,
            Energy = 125,
            Health = 135,
            Image = "MesaPrimeNewLook.png",
            Portrait = "MesaPrimeIcon272.png",
            Mastery = 2,
            Name = "Mesa Prime",
            Polarities = {"Bar", "Bar", "D", "V"},
            Shield = 75,
            Sprint = 1.1,
            Introduced = "24.2.2",
            Sex = "Female"
        },
        ["Mirage"] = {
            Armor = 65,
            AuraPolarity = "Bar",
            Conclave = true,
            Energy = 150,
            Health = 80,
            Image = "MirageNewLook.png",
            Portrait = "MirageIcon272.png",
            Name = "Mirage",
            Polarities = {"D", "V"},
            Shield = 80,
            Sprint = 1.2,
            Introduced = "14",
            Sex = "Female"
        },
        ["Mirage Prime"] = {
            Armor = 150,
            AuraPolarity = "Bar",
            Conclave = true,
            Energy = 150,
            Health = 80,
            Image = "MiragePrimeNewLook.png",
            Portrait = "Mirage PrimeIcon272.png",
            Mastery = 8,
            Name = "Mirage Prime",
            Polarities = {"D", "D", "Bar", "V"},
            Shield = 110,
            Sprint = 1.2,
            Introduced = "22.7",
            Sex = "Female",
            Vaulted = false,
        },
        ["Nekros"] = {
            Armor = 65,
            AuraPolarity = "None",
            Conclave = true,
            Energy = 100,
            Health = 100,
            Image = "NekrosNewLook.png",
            Portrait = "NekrosIcon272.png",
            Name = "Nekros",
            Polarities = {"D", "V"},
            Shield = 90,
            Sprint = 1.1,
            Introduced = "10",
            Sex = "Male",
        },
        ["Nekros Prime"] = {
            Armor = 65,
            AuraPolarity = "None",
            Conclave = true,
            Energy = 125,
            Health = 100,
            Image = "NekrosPrimeNewLook.png",
            Portrait = "Nekros PrimeIcon272.png",
            Name = "Nekros Prime",
            Polarities = {"V", "D", "Bar"},
            Shield = 150,
            Sprint = 1.1,
            Introduced = "The Silver Grove 3",
            Sex = "Male",
            Vaulted = true,
        },
        ["Nezha"] = {
            Armor = 175,
            AuraPolarity = "Bar",
            Conclave = true,
            Energy = 150,
            Health = 125,
            Image = "NezhaNewLook.png",
            Portrait = "NezhaIcon272.png",
            Name = "Nezha",
            Polarities = {"D", "V"},
            Shield = 50,
            Sprint = 1.15,
            Introduced = "18.1",
            Sex = "Male"
        },
        ["Nidus"] = {
            Armor = 300.0,
            ArmorRank30 = 450,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 100,
            Health = 150,
            Image = "NidusNewLook.png",
            Portrait = "NidusIcon272.png",
            Name = "Nidus",
            Polarities = {"V", "D"},
            Shield = 0,
            Sprint = 1,
            Introduced = "19.5",
            Sex = "Male"
        },
        ["Nova"] = {
            Armor = 65,
            AuraPolarity = "Bar",
            Conclave = true,
            Energy = 150,
            Health = 100,
            Image = "NovaNewLook.png",
            Portrait = "NovaIcon272.png",
            Name = "Nova",
            Polarities = {"V", "V"},
            Shield = 75,
            Sprint = 1.2,
            Introduced = "9",
            Sex = "Female",
        },
        ["Nova Prime"] = {
            Armor = 65,
            AuraPolarity = "Bar",
            Conclave = true,
            Energy = 175,
            Health = 100,
            Image = "NovaPrimeNewLook.png",
            Portrait = "Nova PrimeIcon272.png",
            Name = "Nova Prime",
            Polarities = {"V", "V", "V"},
            Shield = 100,
            Sprint = 1.2,
            Introduced = "15.7",
            Sex = "Female",
            Vaulted = false,
        },
        ["Nyx"] = {
            Armor = 15,
            AuraPolarity = "Bar",
            Conclave = true,
            Energy = 150,
            Health = 100,
            Image = "NyxNewLook.png",
            Portrait = "NyxIcon272.png",
            Name = "Nyx",
            Polarities = {"V", "Bar"},
            Shield = 100,
            Sprint = 1.1,
            Introduced = "6",
            Sex = "Female"
        },
        ["Nyx Prime"] = {
            Armor = 50,
            AuraPolarity = "Bar",
            Conclave = true,
            Energy = 150,
            Health = 100,
            Image = "NyxPrimeNewLook.png",
            Portrait = "Nyx PrimeIcon272.png",
            Name = "Nyx Prime",
            Polarities = {"V", "Bar", "D"},
            Shield = 125,
            Sprint = 1.125,
            Introduced = "14.8",
            Sex = "Female",
            Vaulted = true,
        },
        ["Oberon"] = {
            Armor = 150,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 150,
            Health = 125,
            Image = "OberonNewLook.png",
            Portrait = "OberonIcon272.png",
            Name = "Oberon",
            Polarities = {"V", "V"},
            Shield = 100,
            Sprint = 1,
            Introduced = "11.5",
            Sex = "Male"
        },
        ["Oberon Prime"] = {
            Armor = 225,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 175,
            Health = 125,
            Image = "OberonPrimeBust.png",
            Portrait = "Oberon PrimeIcon272.png",
            Mastery = 8,
            Name = "Oberon Prime",
            Polarities = {"Bar", "Bar", "V", "V"},
            Shield = 100,
            Sprint = 1,
            Introduced = "20.6.2",
            Sex = "Male",
            Vaulted = false,
        },
        ["Octavia"] = {
            Armor = 125,
            AuraPolarity = "Bar",
            Conclave = true,
            Energy = 150,
            Health = 100,
            Image = "OctaviaNewLook.png",
            Portrait = "OctaviaIcon272.png",
            Name = "Octavia",
            Polarities = {"Bar", "Bar"},
            Shield = 75,
            Sprint = 1.05,
            Introduced = "20",
            Sex = "Female"
        },
        ["Revenant"] = {
            Armor = 105,
            AuraPolarity = "Bar",
            Conclave = false,
            Energy = 125,
            Health = 100,
            Image = "RevenantNewLook.png",
            Introduced = "23.5",
            Name = "Revenant",
            Polarities = {"V", "D"},
            Portrait = "RevenantIcon272.png",
            Sex = "Male",
            Shield = 225,
            Sprint = 1.00,
            MainCost = {        --Needs to be updated
                Credits = 25000,
                MarketCost = 325,
                Rush = 50,
                Time = 72,
                Parts = {
                    { Name = "Neuroptics",Type = "Item",Count = 1,},
                    { Name = "Chassis",Type = "Item",Count = 1,},
                    { Name = "Systems",Type = "Item",Count = 1,},
                    { Name = "",Type = "Resource",Count = 1,},},
            },
            NeuroCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Neural Sensors",Type = "Resource",Count = 3,},
                    { Name = "Intact Sentient Core",Type = "Resource",Count = 15,},
                    { Name = "Polymer Bundle",Type = "Resource",Count = 6000,},
                    { Name = "Rubedo",Type = "Resource",Count = 2200,},},
            },
            ChassisCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Morphics",Type = "Resource",Count = 3,},
                    { Name = "Intact Sentient Core",Type = "Resource",Count = 10                     ,},
                    { Name = "Rubedo",Type = "Resource",Count = 1500,},
                    { Name = "Iradite",Type = "Resource",Count = 50,},},
            },
            SystemCost = {
                Credits = 15000,
                Rush = 25,
                Time = 12,
                Parts = {
                    { Name = "Control Module",Type = "Resource",Count = 3,},
                    { Name = "Cetus Wisp",Type = "Resource",Count = 3,},
                    { Name = "Salvage",Type = "Resource",Count = 8000,},
                    { Name = "Polymer Bundle",Type = "Resource",Count = 3000,},},
            },
        },
        ["Rhino"] = {
            Armor = 190,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 100,
            Health = 100,
            Image = "RhinoNewLook.png",
            Portrait = "RhinoIcon272.png",
            Introduced = "[[Closed beta updates#Vanilla|Vanilla]]",
            Name = "Rhino",
            Polarities = {"D", "D"},
            Shield = 150,
            Sprint = 0.95,
            Introduced = "Vanilla",
            Sex = "Male"
        },
        ["Rhino Prime"] = {
            Armor = 275,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 100,
            Health = 100,
            Image = "RhinoPrimeNewLook.png",
            Portrait = "Rhino PrimeIcon272.png",
            Name = "Rhino Prime",
            Polarities = {"D", "D", "Bar"},
            Shield = 150,
            Sprint = 1,
            Introduced = "12.4",
            Sex = "Male",
            Vaulted = true,
        },
        ["Saryn"] = {
            Armor = 225,
            AuraPolarity = "D",
            Conclave = true,
            Energy = 150,
            Health = 125,
            Image = "SarynNewLook.png",
            Portrait = "SarynIcon272.png",
            Name = "Saryn",
            Polarities = {"Bar", "D"},
            Shield = 100,
            Sprint = 0.95,
            Introduced = "7",
            Sex = "Female"
        },
        ["Saryn Prime"] = {
            Armor = 300,
            AuraPolarity = "D",
            Conclave = true,
            Energy = 200,
            Health = 125,
            Image = "SarynPrimeLarge.png",
            Portrait = "Saryn PrimeIcon272.png",
            Name = "Saryn Prime",
            Polarities = {"Bar", "D", "V"},
            Shield = 100,
            Sprint = 1,
            Introduced = "18.4.12",
            Sex = "Female",
            Vaulted = true,
        },
        ["Titania"] = {
            Armor = 65,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 150,
            Health = 100,
            Image = "TitaniaNewLook.png",
            Portrait = "TitaniaIcon272.png",
            Name = "Titania",
            Polarities = {"V", "D"},
            Shield = 100,
            Sprint = 1,
            Introduced = "The Silver Grove",
            Sex = "Female",
        },
        ["Trinity"] = {
            Armor = 15,
            AuraPolarity = "D",
            Conclave = true,
            Energy = 150,
            Health = 100,
            Image = "TrinityNewLook.png",
            Portrait = "TrinityIcon272.png",
            Name = "Trinity",
            Polarities = {"D", "D"},
            Shield = 100,
            Sprint = 1,
            Introduced = "Vanilla",
            Sex = "Female"
        },
        ["Trinity Prime"] = {
            Armor = 15,
            AuraPolarity = "D",
            Conclave = true,
            Energy = 150,
            Health = 100,
            Image = "TrinityPrimeMain.png",
            Portrait = "Trinity PrimeIcon272.png",
            Name = "Trinity Prime",
            Polarities = {"D", "D", "V", "Bar"},
            Shield = 150,
            Sprint = 1.1,
            Introduced = "17.6",
            Sex = "Female",
            Vaulted = true,
        },
        ["Valkyr"] = {
            Armor = 600,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 100,
            Health = 100,
            Image = "ValkyrNewLook.png",
            Portrait = "ValkyrIcon272.png",
            Name = "Valkyr",
            Polarities = {"V", "V"},
            Shield = 50,
            Sprint = 1.1,
            Introduced = "11",
            Sex = "Female",
        },
        ["Valkyr Prime"] = {
            Armor = 700,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 150,
            Health = 100,
            Image = "ValkyrPrimeNewLook.png",
            Portrait = "Valkyr PrimeIcon272.png",
            Name = "Valkyr Prime",
            Polarities = {"V", "V", "V"},
            Shield = 50,
            Sprint = 1.1,
            Introduced = "19.0.7",
            Sex = "Female",
            Vaulted = true,
        },
        ["Vauban"] = {
            Armor = 50,
            AuraPolarity = "Bar",
            Conclave = true,
            Energy = 150,
            Health = 100,
            Image = "VaubanNewLook.png",
            Portrait = "VaubanIcon272.png",
            Name = "Vauban",
            Polarities = {"Bar", "V"},
            Shield = 75,
            Sprint = 1,
            Introduced = "7.11",
            Sex = "Male"
        },
        ["Vauban Prime"] = {
            Armor = 100,
            AuraPolarity = "Bar",
            Conclave = true,
            Energy = 150,
            Health = 100,
            Image = "VaubanPrimeNewLook.png",
            Portrait = "Vauban PrimeIcon272.png",
            Name = "Vauban Prime",
            Polarities = {"Bar", "V", "D"},
            Shield = 100,
            Sprint = 1,
            Introduced = "18.12",
            Sex = "Male",
            Vaulted = true,
        },
        ["Volt"] = {
            Armor = 15,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 100,
            Health = 100,
            Image = "VoltNewLook.png",
            Portrait = "VoltIcon272.png",
            Name = "Volt",
            Polarities = {"Bar", "V"},
            Shield = 150,
            Sprint = 1,
            Introduced = "Vanilla",
            Sex = "Male"
        },
        ["Volt Prime"] = {
            Armor = 100,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 200,
            Health = 100,
            Image = "VoltPrimeLarge.png",
            Portrait = "Volt PrimeIcon272.png",
            Name = "Volt Prime",
            Polarities = {"Bar", "V", "V"},
            Shield = 150,
            Sprint = 1,
            Introduced = "16.1",
            Sex = "Male",
            Vaulted = true,
        },
        ["Wukong"] = {
            Armor = 225,
            AuraPolarity = "V",
            Conclave = true,
            Energy = 100,
            Health = 100,
            Image = "WukongNewIcon.png",
            Portrait = "WukongIcon272.png",
            Name = "Wukong",
            Polarities = {"Bar", "D"},
            Shield = 125,
            Sprint = 0.95,
            Introduced = "17.12",
            Sex = "Male"
        },
        ["Zephyr"] = {
            Armor = 15,
            AuraPolarity = "D",
            Conclave = true,
            Energy = 100,
            Health = 150,
            Image = "ZephyrNewLook.png",
            Portrait = "ZephyrIcon272.png",
            Name = "Zephyr",
            Polarities = {"V", "Bar"},
            Shield = 150,
            Sprint = 1.15,
            Introduced = "12",
            Sex = "Female"
        },
        ["Zephyr Prime"] = {
            Mastery = 6,
            Armor = 75,
            AuraPolarity = "D",
            Conclave = true,
            Energy = 150,
            Health = 150,
            Image = "ZephyrPrimeNewLook.png",
            Portrait = "Zephyr PrimeIcon272.png",
            Name = "Zephyr Prime",
            Polarities = {"V", "V", "D", "Bar"},
            Shield = 150,
            Sprint = 1.20,
            Introduced = "22.16.4",
            Sex = "Female",
            Vaulted = false,
        },
    },
}

return WarframeData